### ISSUE TITLE
java.lang.NoSuchFieldException: handle 

### ISSUE THREAD

**Issue by davidvuletas** [honourednihilist/gradle-postgresql-embedded#7]
Hello,

I'm facing with issue using your plugin.
When I try to execute **_./gradlew startPostgres_**, there is a strange situation,after extracting zip i'm receiving error with stacktrace:
```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
        at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
	at ru.yandex.qatools.embed.postgresql.AbstractPGProcess.<init>(AbstractPGProcess.java:19)
......
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
	at com.github.honourednihilist.gradle.postgresql.embedded.EmbeddedPostgres.start(EmbeddedPostgres.java:86)
	at com.github.honourednihilist.gradle.postgresql.embedded.StartPostgresTask.start(StartPostgresTask.java:30)
```

but database is started, and liquibase scripts are executed. 
Do you maybe know, what is the root cause of this error. 
I'm using **_Spring Boot_** with version 2.2.2.RELEASE,
 and **_Gradle Enterprise_** with version 3.0
 and **_Java 11_**

_Thanks in advice!_

**Comment by hovo73** [comment]
This seems to be related to Java 11. I am getting the same exception.

**Comment by p-karanthaker** [comment]
Is there any update on this?
